name: Pull request workflow

on:
  pull_request:
    branches: "main"

jobs:
  pull_request_build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
